# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lesgo-client
    main: ./client/
    binary: lesgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: lesgo-server
    main: ./server/main.go
    binary: server_bin
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the search and replace of the binary name work
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
