# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lesgo-client
    main: ./client/
    binary: lesgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: lesgo-server
    main: ./server/main.go
    binary: server_bin
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the search and replace of the binary name work
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: lesgo
    repository:
      owner: XplnHUB
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/XplnHUB/Les-Go"
    description: "WhatsApp-style CLI chat with E2EE."
    install: |
      bin.install "lesgo"
      bin.install "server_bin"

scoops:
  - name: lesgo
    repository:
      owner: XplnHUB
      name: scoop-bucket
    homepage: "https://github.com/XplnHUB/Les-Go"
    description: "WhatsApp-style CLI chat with E2EE."
    license: MIT

dockers:
  - image_templates:
      - "ghcr.io/xplnhub/lesgo-server:latest"
      - "ghcr.io/xplnhub/lesgo-server:{{ .Version }}"
    dockerfile: server/Dockerfile
    use: buildx
    ids:
      - lesgo-server
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }} relay server"
