name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build Server
      run: go build -v -o server_bin ./server/main.go

    - name: Build Client
      run: go build -v -o lesgo ./client/*.go

    - name: Test
      run: go test -v ./...
